//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThanhVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeWork
    {
        public int IDTimeWork { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> IDEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public override string ToString()
        {
            return StartDate.Value.ToShortTimeString() + "-" + EndDate.Value.ToShortTimeString();
        }
    }
}
